//Note that this extends the global ActorSheet javascript class provided
// by Foundry VTT, NOT the FVTTBridge.ActorSheet class generated by Actor.cs


class ActorSheetGlue extends ActorSheet {

    prepareData() {
        if (typeof this.BridgeActor === 'undefined') {
            this.BridgeActor = FVTTBridge.FoundrySystem.Instance.MakeActor();
        }
        super.prepareData();
        this.data = this.BridgeActor.PrepareData(this.data);
    }

    static get defaultOptions() {
        if (typeof this.BridgeActorSheet === 'undefined') {
            this.BridgeActorSheet = FVTTBridge.FoundrySystem.Instance.MakeActorSheet();
        }
        var options = super.defaultOptions;
        options = this.BridgeActorSheet.GetOptions(options);
        return options;
    }
}