//Note that this extends the global Actor javascript class provided
// by Foundry VTT, NOT the FVTTBridge.Actor class generated by Actor.cs


class ActorGlue extends Actor {

    prepareData() {
        if (typeof this.BridgeActor === 'undefined') {
            this.BridgeActor = FVTTBridge.FoundrySystem.Instance.MakeActor();
        }
        super.prepareData();
        this.data = this.BridgeActor.PrepareData(this.data);
    }

}