//Note that this extends the global Actor javascript class provided
// by Foundry VTT, NOT the FVTTBridge.Actor class generated by Actor.cs


class ActorGlue extends Actor {
    constructor(...args) {
        super(...args);
        this.BridgeActor = FVTTBridge.Bindings.FoundrySystem.Instance.MakeActor();
    }

    prepareData() {
        super.prepareData();
        this.data = this.BridgeActor.PrepareData(this.data);
    }

}