//Note that this extends the global Actor javascript class provided
// by Foundry VTT, NOT the FVTTBridge.Actor class generated by Actor.cs
// The C# FOudnry Actor is stored in Proxy so it can get egneric proxied passthrough


class ActorGlue extends Actor {

    prepareData() {
        if (typeof this.BridgeActor === 'undefined') {
            this.Proxy = FVTTBridge.FoundrySystem.Instance.MakeActor();
        }
        super.prepareData();
        this.data = this.Proxy.PrepareData(this.data);
    }

}