//Note that this extends the global ActorSheet javascript class provided
// by Foundry VTT, NOT the FVTTBridge.ActorSheet class generated by Actor.cs
// The C# FOudnry ActorSheet is stored in Proxy so it can get egneric proxied passthrough


class ActorSheetGlue extends ActorSheet {
    static _ProxyActor;

    static get ProxyActor() {
        if (ActorSheetGlue._ProxyActor === undefined) {
            ActorSheetGlue._ProxyActor = FVTTBridge.FoundrySystem.Instance.MakeActorSheet();
        }
        return ActorSheetGlue._ProxyActor;
    }

    constructor(...args) {
        super(...args);

        return new Proxy(this,
            {
                get: function (target, prop) {
                    if (target[prop] === undefined)
                        if (ActorSheetGlue.ProxyActor[prop] === undefined)
                            return function() {
                                console.log('WARNING: Method invoked by HTML page not defined on Actor: '+prop);
                            };
                        else
                            return ActorSheetGlue.ProxyActor[prop];
                    else
                        return target[prop];
                }
            });
    }

    static get defaultOptions() {
        var options = super.defaultOptions;
        options = ActorSheetGlue.ProxyActor.GetOptions(options);
        return options;
    }

    activateListeners(html) {
        super.activateListeners(html);
        ActorSheetGlue.ProxyActor.ActivateListeners(html);
    }
}